/*
 * Vultiserver API
 *
 * TSS (Threshold Signature Scheme) server for keygen, keysign, and reshare operations supporting ECDSA, EdDSA, and MLDSA via GG20 and DKLS protocols.  Vultiserver runs an Echo HTTP server and an asynq worker for async TSS operations backed by Redis. Most mutating endpoints enqueue an async task and return immediately. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultCreateCheckResponse {
    /// \"ongoing\" while the ceremony is running, \"complete\" when finished
    #[serde(rename = "status")]
    pub status: Status,
    /// Hex-encoded ECDSA public key (present when status is \"complete\")
    #[serde(rename = "public_key_ecdsa", skip_serializing_if = "Option::is_none")]
    pub public_key_ecdsa: Option<String>,
    /// Hex-encoded EdDSA public key (present when status is \"complete\")
    #[serde(rename = "public_key_eddsa", skip_serializing_if = "Option::is_none")]
    pub public_key_eddsa: Option<String>,
}

impl VaultCreateCheckResponse {
    pub fn new(status: Status) -> VaultCreateCheckResponse {
        VaultCreateCheckResponse {
            status,
            public_key_ecdsa: None,
            public_key_eddsa: None,
        }
    }
}
/// \"ongoing\" while the ceremony is running, \"complete\" when finished
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ongoing")]
    Ongoing,
    #[serde(rename = "complete")]
    Complete,
    #[serde(rename = "unknown_default_open_api")]
    UnknownDefaultOpenApi,
}

impl Default for Status {
    fn default() -> Status {
        Self::Ongoing
    }
}

